// Generated by CoffeeScript 1.9.3
(function() {
  var createItem, createRow, getASkeleton, getImageSkeleton, getTileSkeleton, iconclass, icondivSkeleton, imageKindToString, imageSkeleton, imageclass, makeLogos, placeShortcuts;

  placeShortcuts = function(shortcuts, itemsPerRow) {
    var i, len, list, results, row;
    list = $("#shortcut-list");
    results = [];
    for (i = 0, len = shortcuts.length; i < len; i++) {
      row = shortcuts[i];
      results.push(list.append(createRow(row, itemsPerRow)));
    }
    return results;
  };

  createRow = function(row, itemsPerRow) {
    var i, item, jqueryRow, len;
    console.log("Row created.");
    jqueryRow = $("<div class='row tile-row'></div>");
    for (i = 0, len = row.length; i < len; i++) {
      item = row[i];
      jqueryRow.append(createItem(item, 12 / itemsPerRow));
    }
    return jqueryRow;
  };

  iconclass = "text-center pagination-centered tile";

  imageclass = "logo-";

  icondivSkeleton = "<div class='" + iconclass + "'></div>";

  imageSkeleton = "<img class='" + imageclass + "' src='../images/logos/'></img>";

  getTileSkeleton = function(colSize) {
    return "<div class='col-xs-" + colSize + "'></div>";
  };

  getASkeleton = function(url) {
    return "<a href='" + url + "' class='link-tile'></a>";
  };

  getImageSkeleton = function(name, cssClass) {
    return "<img class='" + cssClass + "' src='../images/logos/" + name + ".png'></img>";
  };

  imageKindToString = function(square) {
    if (square) {
      return "square";
    } else {
      return "rect";
    }
  };

  createItem = function(item, colSize) {
    var A, DIV, IMG, TILE, b, bgcolor, g, imagecssclass, imagename, kindString, r, ref;
    ref = item.bgcolor, r = ref[0], g = ref[1], b = ref[2];
    bgcolor = item.bgcolor;
    kindString = imageKindToString(item.square);
    imagename = item.logoid + "-" + kindString;
    imagecssclass = imageclass + kindString;
    IMG = $(getImageSkeleton(imagename, imagecssclass));
    A = $(getASkeleton(item.url));
    DIV = $(icondivSkeleton);
    TILE = $(getTileSkeleton(colSize));
    DIV.css("background-color", rgbaString(r, g, b, 0.5));
    if (item.logobordercolor != null) {
      IMG.css("border", "1px solid " + item.logobordercolor);
    }
    if (item.bordercolor != null) {
      DIV.css("border", "1px solid " + item.bordercolor);
    }
    DIV.append(IMG);
    A.append(DIV);
    TILE.append(A);
    return TILE;
  };

  makeLogos = function() {
    var full, ref, square;
    ref = splitBy("square", shortcuts), square = ref[0], full = ref[1];
    full = split(full, 4);
    square = split(square, 6);
    console.log(full);
    console.log(square);
    placeShortcuts(full, 4);
    return placeShortcuts(square, 6);
  };

}).call(this);
