// Generated by CoffeeScript 1.9.3
(function() {
  var setBG;

  setBG = function() {
    var r;
    r = Math.floor((Math.random() * 2) + 1);
    return document.body.style.backgroundImage = "url('../images/wallpapers/default.jpg')";
  };

  setBG();

  makeLogos();

  makeTimeTable();

}).call(this);
