// Generated by CoffeeScript 1.9.3
(function() {
  var classes, shortcuts, sidebar;

  shortcuts = [
    {
      name: "mensa",
      url: "http://www.studentenwerk-saarland.de/en/Essen/Essen-in-Saarbrucken/Speiseplan-aktuell",
      bgcolor: [255, 255, 255],
      logoid: "studentenwerk",
      square: true
    }, {
      name: "GitHub",
      url: "http://github.com",
      bgcolor: [255, 255, 255],
      logoid: "github-alternative",
      square: true
    }, {
      name: "amazon",
      url: "http://amazon.de",
      bgcolor: [255, 255, 255],
      logoid: "amazon",
      square: true
    }, {
      name: "youtube",
      url: "http://youtube.com",
      bgcolor: [255, 255, 255],
      logoid: "youtube",
      square: true
    }, {
      name: "lsf",
      url: "http://www.lsf.uni-saarland.de",
      bgcolor: [255, 255, 255],
      logoid: "uds",
      square: true
    }, {
      name: "google+",
      url: "http://plus.google.com",
      bgcolor: [255, 255, 255],
      logoid: "g+",
      square: true
    }, {
      name: "linkedin",
      url: "http://linkedin.com",
      bgcolor: [255, 255, 255],
      logoid: "linkedin",
      square: true
    }, {
      name: "calendar",
      url: "http://calendar.google.com",
      bgcolor: [255, 255, 255],
      logoid: "calendar",
      square: true
    }, {
      name: "dictcc",
      url: "http://dict.cc",
      bgcolor: [255, 255, 255],
      logoid: "dictcc",
      square: true
    }, {
      name: "swr3",
      url: "http://swr3.de",
      bgcolor: [255, 255, 255],
      logoid: "swr3",
      square: true
    }
  ];

  classes = [
    {
      name: "Multicore System Architecture",
      short: "SysArch II",
      color: [0, 122, 41],
      link: "https://www.lsf.uni-saarland.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=90532&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung",
      periods: [
        {
          weekday: weekday("Tuesday"),
          begin: beginId(1400),
          duration: 4,
          room: "E1.3 HS III",
          tutorial: false
        }, {
          weekday: weekday("Fryday"),
          begin: beginId(1000),
          duration: 4,
          room: "E1.3 HS III",
          tutorial: false
        }
      ]
    }, {
      name: "Database Management Systems",
      short: "DBMS",
      color: [255, 204, 0],
      link: "https://infosys.uni-saarland.de/teaching/ws15/dbms.php",
      periods: [
        {
          weekday: weekday("Thursday"),
          begin: beginId(1000),
          duration: 4,
          room: "E1.3 HS II",
          tutorial: false
        }
      ]
    }, {
      name: "Automated Reasoning",
      short: "Reasoning",
      color: [153, 0, 0],
      link: "https://www.lsf.uni-saarland.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=89924&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung",
      periods: [
        {
          weekday: weekday("Monday"),
          begin: beginId(1600),
          duration: 4,
          room: "E1.3 HS III",
          tutorial: false
        }, {
          weekday: weekday("Thursday"),
          begin: beginId(1200),
          duration: 4,
          room: "E1.3 HS III",
          tutorial: false
        }
      ]
    }, {
      name: "Machine Learning",
      short: "ML",
      color: [0, 102, 255],
      link: "http://www.ml.uni-saarland.de/Lectures/ML1516/ML1516.htm",
      periods: [
        {
          weekday: weekday("Wednesday"),
          begin: beginId(1400),
          duration: 4,
          room: "E1.3 HS I",
          tutorial: false
        }, {
          weekday: weekday("Fryday"),
          begin: beginId(1000),
          duration: 4,
          room: "E1.3 HS I",
          tutorial: false
        }
      ]
    }, {
      name: "Deep Learning",
      short: "Deep Learning",
      color: [204, 204, 204],
      link: "https://infosys.uni-saarland.de/teaching/ws15/deep%20learning.php",
      periods: [
        {
          weekday: weekday("Additional"),
          begin: beginId(800),
          duration: 4,
          tutorial: false
        }
      ]
    }, {
      name: "Admissible Search Enhancements",
      short: "Planning",
      color: [204, 204, 204],
      link: "http://fai.cs.uni-saarland.de/teaching/winter15-16/search-enhancements.html",
      periods: [
        {
          weekday: weekday("Additional"),
          begin: beginId(1000),
          duration: 4,
          tutorial: false
        }
      ]
    }
  ];

  sidebar = [
    {
      name: "preferences",
      icon: "cog.png",
      call: "show_preferences()"
    }, {
      name: "timetable",
      icon: "timetable.png",
      call: "show_timetable()"
    }, {
      name: "swr3",
      icon: "swr3.png",
      call: "trigger_swr3()"
    }
  ];

}).call(this);
