// Generated by CoffeeScript 1.9.3
(function() {
  var show_preferences, trigger_swr3;

  show_preferences = function() {
    return 0;
  };

  trigger_swr3 = function() {
    return chrome.runtime.sendMessage({
      intent: "trigger_swr3"
    }, function(response) {
      return console.log(response);
    });
  };

}).call(this);
